//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trabajo1ServiciosWebJueves6a8.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class computador
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public computador()
        {
            this.Ventas = new HashSet<Venta>();
        }
    
        public int idcomputador { get; set; }
        public Nullable<int> numeroProcesadores { get; set; }
        public string marcaProcesador { get; set; }
        public string TamañoDiscoDuro { get; set; }
        public string DetalleComponentes { get; set; }
        public Nullable<int> IdTipoComputador { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<Venta> Ventas { get; set; }
        [JsonIgnore]
        public virtual tipoComputador tipoComputador { get; set; }
    }
}
