//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trabajo1ServiciosWebJueves6a8.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        public int Idventa { get; set; }
        public Nullable<System.DateTime> Fecha_hora { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<int> IdAgencia { get; set; }
        public Nullable<int> idCliente { get; set; }
        public Nullable<int> idcomputador { get; set; }

        [JsonIgnore]
        public virtual Agencia Agencia { get; set; }
        [JsonIgnore]
        public virtual Cliente Cliente { get; set; }
        [JsonIgnore]
        public virtual computador computador { get; set; }
    }
}
